config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :users do
    resources :members do
      get :status
      post :aggregate
    end

    resources :accounts
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :member
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_user

  def index
    mxplatform_accounts = MXPlatformRuby::Account.list_user_accounts(account_params)
    @accounts = mxplatform_accounts
  end

private
  def account_params
    account_params = params.fetch(:account, {}).permit(
      :user_id,
      :id,
      :account_id
    )
    account_params[:user_guid] = @user.guid
    account_params
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ aggregate show edit update destroy status ]
  before_action :set_user

  # POST /users/{user_guid}/members/{member_guid}/aggregate
  def aggregate
    mxplatform_member = MXPlatformRuby::Member.aggregate_member(aggregation_params)
    @member.update(
      :aggregated_at => mxplatform_member.aggregated_at,
      :connection_status => mxplatform_member.connection_status,
      :is_being_aggregated => mxplatform_member.is_being_aggregated,
      :successfully_aggregated_at => mxplatform_member.successfully_aggregated_at
    )
    redirect_to user_member_path(@user, @member)
  end

  # GET /members or /members.json
  def index
    @members = Member.where(:user_id => @user.id)
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members or /members.json
  def create
    mx_member = MXPlatformRuby::Member.create_member(member_params)
    local_member_params = {}
    local_member_params[:aggregated_at] = mx_member.aggregated_at
    local_member_params[:guid] = mx_member.guid
    local_member_params[:institution_code] = mx_member.institution_code
    local_member_params[:mx_id] = mx_member.id
    local_member_params[:name] = mx_member.name
    local_member_params[:status] = mx_member.status
    local_member_params[:user_id] = @user.id
    local_member_params[:successfully_aggregated_at] = mx_member.successfully_aggregated_at
    local_member_params[:is_being_aggregated] = mx_member.is_being_aggregated

    @member = Member.new(local_member_params)
    respond_to do |format|
      if @member.save
        format.html { redirect_to user_member_path(@user, @member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /users/{user_guid}/members/{member_guid}/status
  def status
    mxplatform_member = MXPlatformRuby::MemberStatus.read_member_status(aggregation_params)
    @member.update(
      :aggregated_at => mxplatform_member.aggregated_at,
      :connection_status => mxplatform_member.connection_status,
      :is_being_aggregated => mxplatform_member.is_being_aggregated,
      :successfully_aggregated_at => mxplatform_member.successfully_aggregated_at
    )
    redirect_to user_member_path(@user, @member)
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      member_id = params[:id] if params[:id]
      member_id = params[:member_id] if params[:member_id]

      @member = Member.find(member_id)
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Only allow a list of trusted parameters through.
    def member_params
      member_params = params.fetch(:member, {}).permit(
        :credential_a_guid,
        :credential_a_value,
        :credential_b_guid,
        :credential_b_value,
        :mx_id,
        :institution_code,
        :user_id
      )
      member_params[:credentials] = [
        {
          :guid => member_params[:credential_a_guid],
          :value => member_params[:credential_a_value]
        },
        {
          :guid => member_params[:credential_b_guid],
          :value => member_params[:credential_b_value]
        }
      ]
      member_params[:user_guid] = user_guid
      # Workaround for permission problems with credentials.
      # TODO: figure out proper way to permission credentials field and not use .to_h
      member_params.to_h
    end

    def aggregation_params
      aggregation_params = params.fetch(:member, {}).permit(
        :user_id,
        :member_id
      )
      aggregation_params[:user_guid] = @user.guid
      aggregation_params[:member_guid] = @member.guid
      aggregation_params
    end

    def user_guid
      User.find(params[:user_id]).guid
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  # GET /
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    user_params[:id] = user_params[:mx_id]
    mx_user = MXPlatformRuby::User.create_user(user_params)
    mx_user_params = {}
    mx_user_params[:mx_id] = mx_user.id
    mx_user_params[:email] = mx_user.email
    mx_user_params[:guid] = mx_user.guid

    @user = User.new(mx_user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, { }).permit(:email, :mx_id, :is_disabled, :metadata)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td>guid: <%= account.guid %></td>
      </tr>
      <tr>
        <td>balance: <%= account.balance %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'User', user_path(@user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleAgg</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/members/_form.html.erb
<%= form_with(model: member, url: user_members_path) do |form| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :credential_a_guid, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :credential_a_guid, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= form.label :credential_a_value, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :credential_a_value, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :credential_b_guid, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :credential_b_guid, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :credential_b_value, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :credential_b_value, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :institution_code, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :institution_code, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :mx_id, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :mx_id, :class => "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_status.html.erb
<p>
  status: <%= member.connection_status %>
</p>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', user_members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Members</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td>id: <%= member.id %></td>
      </tr>
      <tr>
        <td>mx_id: <%= member.mx_id %></td>
      </tr>
      <tr>
        <td>name: <%= member.name %></td>
      </tr>
      <tr>
        <td>institution_code: <%= member.institution_code %></td>
      </tr>
      <tr>
        <td>guid: <%= member.guid %></td>
      </tr> 
      <tr>
        <td><%= link_to 'Show', user_member_path(member.user, member) %></td>
        <td><%= link_to 'Edit', edit_user_member_path(member.user, member) %></td>
        <td><%= link_to 'Destroy', user_member_path(member.user, member), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_user_member_path %> |
<%= link_to 'Back to User', user_path(@user) %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', user_members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Member <%= @member.id %></h1>
<%= link_to 'Aggregate', "#{user_member_path}/aggregate", :method => :post %>
<%= link_to 'Check Status', "#{user_member_path}/status" %>
<%= render 'status', member: @member %>

<table>
  <thead>
    <tr>
      <th colspan="3">Details </th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>aggregated_at: <%= @member.aggregated_at %></td>
      </tr>
      <tr>
        <td>guid: <%= @member.guid %></td>
      </tr>
      <tr>
        <td>institution_code: <%= @member.institution_code %></td>
      </tr>
      <tr>
        <td>is_being_aggregated: <%= @member.is_being_aggregated %></td>
      </tr>
      <tr>
        <td>mx_id: <%= @member.mx_id %></td>
      </tr>
      <tr>
        <td>successfully_aggregated_at: <%= @member.successfully_aggregated_at %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Accounts', user_accounts_path(@user) %>
<%= link_to 'Edit', edit_user_member_path(@member) %> |
<%= link_to 'Back', user_members_path %>

app/views/pages/index.html.erb
<h1>Welcome to Sample Aggregation App</h1>

<%= link_to 'Users', users_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :email, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :mx_id, :class => "col-xs-2 control-label" %>
    <div class="col-xs-4">
        <%= form.text_field :mx_id, :class => "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td>id: <%= user.id %></td>
      </tr>
      <tr>
        <td>mx_id: <%= user.mx_id %></td>
      </tr>
      <tr>
        <td>email: <%= user.email %></td>
      </tr>
      <tr>
        <td>guid: <%= user.guid %></td>
      </tr>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>User <%= @user.id %></h1>
<table>
  <thead>
    <tr>
      <th colspan="3">Details</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>mx_id: <%= @user.mx_id %></td>
      </tr>
      <tr>
        <td>email: <%= @user.email %></td>
      </tr>
      <tr>
        <td>guid: <%= @user.guid %></td>
      </tr>
  </tbody>
</table>

<%= link_to 'Accounts', user_accounts_path(@user) %>
<%= link_to 'Members', user_members_path(@user) %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>